import React, { useState } from 'react';
import { Play, Settings, Shield, Sliders } from 'lucide-react';
import { api } from '../lib/api';
import type { CreateRunRequest } from '../types';

interface NewRunProps {
  onRunCreated: (runId: string) => void;
  onCancel: () => void;
}

export const NewRun: React.FC<NewRunProps> = ({ onRunCreated, onCancel }) => {
  const [scenario, setScenario] = useState<
    'stationary' | 'abrupt' | 'gradual' | 'recurring' | 'rare_region' | 'adversary'
  >('abrupt');
  const [nEvents, setNEvents] = useState<number>(2000);
  const [warmupSize, setWarmupSize] = useState<number>(200);
  const [labelBudget, setLabelBudget] = useState<number>(300);
  const [labelDelay, setLabelDelay] = useState<number>(0);
  const [seed, setSeed] = useState<number>(42);
  const [driftStartSeq, setDriftStartSeq] = useState<string>('');
  const [gradualWindow, setGradualWindow] = useState<number>(400);
  const [recurrenceInterval, setRecurrenceInterval] = useState<number>(500);
  const [rareRegionP, setRareRegionP] = useState<number>(0.05);
  const [adversaryDwell, setAdversaryDwell] = useState<number>(300);
  const [adwinDelta, setAdwinDelta] = useState<number>(0.002);
  const [targetTrainingLabels, setTargetTrainingLabels] = useState<number>(200);
  const [evaluationTargetEvents, setEvaluationTargetEvents] = useState<number>(500);
  const [eventsPerSecond, setEventsPerSecond] = useState<number>(100.0);

  // Client idempotency key generated by default
  const [idempotencyKey, setIdempotencyKey] = useState<string>(
    () => `client-${Date.now().toString(36)}-${Math.random().toString(36).substring(2, 6)}`
  );

  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);

    // Validation
    if (warmupSize >= nEvents) {
      setError(`Warmup size (${warmupSize}) must be strictly less than total stream events (${nEvents}).`);
      return;
    }

    if (labelBudget < 0) {
      setError('Label budget must be non-negative.');
      return;
    }

    setIsLoading(true);
    try {
      const payload: CreateRunRequest = {
        scenario,
        n_events: nEvents,
        warmup_size: warmupSize,
        label_budget: labelBudget,
        label_delay: labelDelay,
        seed,
        drift_start_sequence: driftStartSeq ? parseInt(driftStartSeq, 10) : null,
        gradual_window: scenario === 'gradual' ? gradualWindow : undefined,
        recurrence_interval: scenario === 'recurring' ? recurrenceInterval : undefined,
        rare_region_p: scenario === 'rare_region' ? rareRegionP : undefined,
        adversary_dwell: scenario === 'adversary' ? adversaryDwell : undefined,
        adwin_delta: adwinDelta,
        target_training_labels: targetTrainingLabels,
        evaluation_target_events: evaluationTargetEvents,
        events_per_second: eventsPerSecond,
        idempotency_key: idempotencyKey.trim() || undefined,
      };

      const result = await api.createRun(payload);
      // Never assume returned run_id; use server-returned identifier
      if (!result?.run_id) {
        throw new Error('Server did not return a valid run_id');
      }
      onRunCreated(result.run_id);
    } catch (err: any) {
      setError(err?.message || 'Failed to create simulation run');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div style={{ maxWidth: '800px', margin: '0 auto', display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
      <div>
        <h1 style={{ fontSize: '1.5rem', fontWeight: 700, color: 'var(--text-primary)' }}>
          Create Simulation Run
        </h1>
        <p style={{ color: 'var(--text-secondary)', fontSize: '0.875rem' }}>
          Configure stream generation parameters, labeling budget, ADWIN detection confidence, and candidate adaptation settings.
        </p>
      </div>

      {error && (
        <div
          style={{
            padding: '1rem',
            backgroundColor: 'var(--danger-bg)',
            color: 'var(--danger-text)',
            border: '1px solid var(--danger-border)',
            borderRadius: 'var(--radius-sm)',
            fontSize: '0.875rem',
          }}
        >
          {error}
        </div>
      )}

      <form onSubmit={handleSubmit} className="card" style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
        {/* Stream Scenario & Pacing */}
        <div>
          <div style={{ fontWeight: 600, fontSize: '0.9375rem', marginBottom: '0.75rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <Sliders size={16} color="var(--cobalt-600)" />
            Stream Scenario & Event Generator
          </div>

          <div className="grid-3">
            <div className="form-group">
              <label className="form-label" htmlFor="scenario">Scenario Type</label>
              <select
                id="scenario"
                className="form-select"
                value={scenario}
                onChange={(e) => setScenario(e.target.value as any)}
              >
                <option value="abrupt">Abrupt Drift (Concept Shift)</option>
                <option value="stationary">Stationary Stream (No Drift)</option>
                <option value="gradual">Gradual Drift (Mixture Transition)</option>
                <option value="recurring">Recurring Drift (A-B-A Periodic)</option>
                <option value="rare_region">Rare-Region Stealth Drift</option>
                <option value="adversary">Adaptive Adversary (Margin Maximizing)</option>
              </select>
              <span className="form-help">Scenario controls deterministic feature generator</span>
            </div>

            <div className="form-group">
              <label className="form-label" htmlFor="seed">RNG Seed</label>
              <input
                id="seed"
                type="number"
                className="form-input"
                value={seed}
                onChange={(e) => setSeed(parseInt(e.target.value, 10) || 0)}
                required
              />
              <span className="form-help">Deterministic seed for exact reproducibility</span>
            </div>

            <div className="form-group">
              <label className="form-label" htmlFor="drift_start_sequence">Drift Start Sequence (Optional)</label>
              <input
                id="drift_start_sequence"
                type="number"
                className="form-input"
                placeholder="Default: midpoint"
                value={driftStartSeq}
                onChange={(e) => setDriftStartSeq(e.target.value)}
              />
              <span className="form-help">Sequence index where concept shift begins</span>
            </div>
          </div>

          {/* Contextual Scenario Parameters */}
          {scenario === 'gradual' && (
            <div className="grid-3" style={{ marginTop: '0.75rem' }}>
              <div className="form-group">
                <label className="form-label" htmlFor="gradual_window">Gradual Window (Events)</label>
                <input
                  id="gradual_window"
                  type="number"
                  className="form-input"
                  value={gradualWindow}
                  min={10}
                  max={5000}
                  onChange={(e) => setGradualWindow(parseInt(e.target.value, 10) || 400)}
                  required
                />
                <span className="form-help">Transition length over which mixture probability shifts 0 ➔ 1</span>
              </div>
            </div>
          )}

          {scenario === 'recurring' && (
            <div className="grid-3" style={{ marginTop: '0.75rem' }}>
              <div className="form-group">
                <label className="form-label" htmlFor="recurrence_interval">Recurrence Interval (Events)</label>
                <input
                  id="recurrence_interval"
                  type="number"
                  className="form-input"
                  value={recurrenceInterval}
                  min={10}
                  max={5000}
                  onChange={(e) => setRecurrenceInterval(parseInt(e.target.value, 10) || 500)}
                  required
                />
                <span className="form-help">Period in stream events between A ➔ B ➔ A concept switches</span>
              </div>
            </div>
          )}

          {scenario === 'rare_region' && (
            <div className="grid-3" style={{ marginTop: '0.75rem' }}>
              <div className="form-group">
                <label className="form-label" htmlFor="rare_region_p">Rare-Region Mass (p)</label>
                <input
                  id="rare_region_p"
                  type="number"
                  className="form-input"
                  value={rareRegionP}
                  min={0.001}
                  max={0.5}
                  step="any"
                  onChange={(e) => setRareRegionP(parseFloat(e.target.value) || 0.05)}
                  required
                />
                <span className="form-help">Fraction of feature space where concept changes stealthily</span>
              </div>
            </div>
          )}

          {scenario === 'adversary' && (
            <div className="grid-3" style={{ marginTop: '0.75rem' }}>
              <div className="form-group">
                <label className="form-label" htmlFor="adversary_dwell">Adversary Dwell (Events)</label>
                <input
                  id="adversary_dwell"
                  type="number"
                  className="form-input"
                  value={adversaryDwell}
                  min={50}
                  max={5000}
                  onChange={(e) => setAdversaryDwell(parseInt(e.target.value, 10) || 300)}
                  required
                />
                <span className="form-help">Dwell interval between adaptive rule switches based on past margins</span>
              </div>
            </div>
          )}

          <div className="grid-3">
            <div className="form-group">
              <label className="form-label" htmlFor="n_events">Total Stream Events (n_events)</label>
              <input
                id="n_events"
                type="number"
                className="form-input"
                value={nEvents}
                min={10}
                max={100000}
                onChange={(e) => setNEvents(parseInt(e.target.value, 10) || 1000)}
                required
              />
            </div>

            <div className="form-group">
              <label className="form-label" htmlFor="warmup_size">Warmup Events</label>
              <input
                id="warmup_size"
                type="number"
                className="form-input"
                value={warmupSize}
                min={1}
                max={5000}
                onChange={(e) => setWarmupSize(parseInt(e.target.value, 10) || 200)}
                required
              />
              <span className="form-help">Initial classifier training buffer</span>
            </div>

            <div className="form-group">
              <label className="form-label" htmlFor="events_per_second">Simulation Clock Speed (eps)</label>
              <input
                id="events_per_second"
                type="number"
                className="form-input"
                value={eventsPerSecond}
                min={1}
                max={5000}
                step="any"
                onChange={(e) => setEventsPerSecond(parseFloat(e.target.value) || 100)}
                required
              />
              <span className="form-help">Monotonic rate pacing (events/sec)</span>
            </div>
          </div>
        </div>

        {/* Labeling Policy & Delays */}
        <div style={{ borderTop: '1px solid var(--border-subtle)', paddingTop: '1.25rem' }}>
          <div style={{ fontWeight: 600, fontSize: '0.9375rem', marginBottom: '0.75rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <Shield size={16} color="var(--cobalt-600)" />
            Labeling Policy & Channel Budget
          </div>

          <div className="grid-2">
            <div className="form-group">
              <label className="form-label" htmlFor="label_budget">Post-Warmup Label Budget</label>
              <input
                id="label_budget"
                type="number"
                className="form-input"
                value={labelBudget}
                min={0}
                onChange={(e) => setLabelBudget(parseInt(e.target.value, 10) || 0)}
                required
              />
              <span className="form-help">Strict budget ceiling for post-warmup label acquisitions</span>
            </div>

            <div className="form-group">
              <label className="form-label" htmlFor="label_delay">Label Delivery Delay (events)</label>
              <input
                id="label_delay"
                type="number"
                className="form-input"
                value={labelDelay}
                min={0}
                max={500}
                onChange={(e) => setLabelDelay(parseInt(e.target.value, 10) || 0)}
                required
              />
              <span className="form-help">Logical event delay before label arrival (0 = immediate)</span>
            </div>
          </div>
        </div>

        {/* ADWIN & Candidate Adaptation */}
        <div style={{ borderTop: '1px solid var(--border-subtle)', paddingTop: '1.25rem' }}>
          <div style={{ fontWeight: 600, fontSize: '0.9375rem', marginBottom: '0.75rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <Settings size={16} color="var(--cobalt-600)" />
            Detection & Statistical Evaluation
          </div>

          <div className="grid-3">
            <div className="form-group">
              <label className="form-label" htmlFor="adwin_delta">ADWIN Delta Confidence</label>
              <input
                id="adwin_delta"
                type="number"
                className="form-input"
                value={adwinDelta}
                min={0.0001}
                max={0.5}
                step="any"
                onChange={(e) => setAdwinDelta(parseFloat(e.target.value) || 0.002)}
                required
              />
            </div>

            <div className="form-group">
              <label className="form-label" htmlFor="target_training_labels">Target Training Labels</label>
              <input
                id="target_training_labels"
                type="number"
                className="form-input"
                value={targetTrainingLabels}
                min={5}
                max={2000}
                onChange={(e) => setTargetTrainingLabels(parseInt(e.target.value, 10) || 200)}
                required
              />
            </div>

            <div className="form-group">
              <label className="form-label" htmlFor="evaluation_target_events">Paired Evaluation Target</label>
              <input
                id="evaluation_target_events"
                type="number"
                className="form-input"
                value={evaluationTargetEvents}
                min={5}
                max={5000}
                onChange={(e) => setEvaluationTargetEvents(parseInt(e.target.value, 10) || 500)}
                required
              />
            </div>
          </div>

          <div className="form-group">
            <label className="form-label" htmlFor="idempotency_key">Client Idempotency Key</label>
            <input
              id="idempotency_key"
              type="text"
              className="form-input"
              value={idempotencyKey}
              onChange={(e) => setIdempotencyKey(e.target.value)}
              placeholder="e.g. client-key-001"
            />
            <span className="form-help">Prevents duplicate run creation on network retries</span>
          </div>
        </div>

        {/* Buttons */}
        <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '0.75rem', borderTop: '1px solid var(--border-subtle)', paddingTop: '1.25rem' }}>
          <button type="button" className="btn btn-secondary" onClick={onCancel} disabled={isLoading}>
            Cancel
          </button>
          <button id="btn-create-run" type="submit" className="btn btn-primary" disabled={isLoading}>
            <Play size={14} /> {isLoading ? 'Creating Run...' : 'Initialize & Open Dashboard'}
          </button>
        </div>
      </form>
    </div>
  );
};
